### ISSUE TITLE
Creating an MP4 File Even When Requesting MP3

### ISSUE THREAD

**Issue by feijoes** [En7ity303/youtube-downloader#1]
I am using Ubuntu 22.02, and I am attempting to download a video in MP3 format. However, I've noticed that the downloader is also downloading an MP4 file alongside the MP3 file.

**Comment by En7ity303** [comment]
I know that issue, i'm still searching a way to fix it, if you have any suggestions told me I will appreciate it, it's a while since I have searching a solution and I haven't found one yet

**Comment by En7ity303** [comment]
I have updated a little bit the script, now while downloading an mp3 file it download it as  mp4, convert it to mp3 and then delete the mp4 file
